/// x1zz-compiler/src/emitter.rs — Rust 코드 에밋 (Transpiler Layer) v0.16
///
/// .xzz 스크립트 → 독립 실행 가능한 Rust + Polars 소스 코드 생성기.
///
/// [v0.16 변경사항]
///   - BoolLit 지원 (to_typed_polars_expr)
///   - Count(None) / Count(Some(col)) 구분
///   - 신규 연산자 코드 생성:
///       GroupBy + 집계 연산자 → .group_by([...]).agg([...]) 페어링
///       OrderBy → .sort([...], SortMultipleOptions)
///       Take → .limit(n)
///       DropNull → .drop_nulls(Some(vec![...]))
///       FillNull → .with_columns([...fill_null(...)])
///   - validate_op_columns: 신규 컬럼 인수 연산자 스키마 검증 추가

use std::collections::HashMap;
use std::fs;

use crate::ast::{BinOpKind, Expr, FillNullValue, PipelineOp, PipelineSource, Program, Stmt};
use crate::{Codegen, Lexer, Parser, StructField};

// ─────────────────────────────────────────────────────────────────────────────
// ── 공개 진입점 ───────────────────────────────────────────────────────────────
// ─────────────────────────────────────────────────────────────────────────────

/// .xzz 파일을 독립 실행 가능한 Rust 소스 코드로 변환한다.
pub fn emit_rust(
    source_path: &str,
    out_path: Option<&str>,
) -> Result<(), Box<dyn std::error::Error>> {
    // ── Step 1: 소스 파일 읽기 ───────────────────────────────────────────────
    let source = fs::read_to_string(source_path)
        .map_err(|e| format!("IO 에러: 파일 읽기 실패 '{}' — {}", source_path, e))?;

    // ── Step 2: 렉서 ────────────────────────────────────────────────────────
    let mut lexer = Lexer::new(&source);
    let tokens = lexer.tokenize().map_err(|e| format!("{}", e))?;

    // ── Step 3: 파서 ────────────────────────────────────────────────────────
    let mut parser = Parser::new(tokens);
    let program = parser.parse().map_err(|e| format!("{}", e))?;

    // ── Step 4: 스키마 검증 + Rust 코드 생성 ────────────────────────────────
    let rust_code = generate_rust_src(&program, source_path)?;

    // ── Step 5: 출력 ────────────────────────────────────────────────────────
    match out_path {
        Some(path) => {
            fs::write(path, &rust_code)
                .map_err(|e| format!("IO 에러: 출력 파일 쓰기 실패 '{}' — {}", path, e))?;

            println!("✅  emit rust 완료 → {}", path);
            println!();
            println!("─── 실행 방법 ──────────────────────────────────────────────────");
            println!("  1) 새 Rust 프로젝트 생성:");
            println!("       cargo new my_analysis && cd my_analysis");
            println!("  2) Cargo.toml 에 의존성 추가:");
            println!("       polars      = {{ version = \"0.53\", features = [\"lazy\", \"csv\"] }}");
            println!("       encoding_rs = \"0.8\"");
            println!("  3) {} 를 src/main.rs 로 복사 후 실행:", path);
            println!("       cargo run");
            println!("────────────────────────────────────────────────────────────────");
        }
        None => println!("{}", rust_code),
    }

    Ok(())
}

// ─────────────────────────────────────────────────────────────────────────────
// ── 내부: AST → Rust 소스 문자열 생성 ─────────────────────────────────────────
// ─────────────────────────────────────────────────────────────────────────────

fn generate_rust_src(
    program: &Program,
    source_path: &str,
) -> Result<String, Box<dyn std::error::Error>> {
    // ── 전역 스키마 맵 구축 ──────────────────────────────────────────────────
    let mut schema_map: HashMap<String, Vec<StructField>> = HashMap::new();
    for stmt in &program.stmts {
        if let Stmt::TypeDecl { name, fields } = stmt {
            schema_map.insert(name.clone(), fields.clone());
        }
    }

    let mut out = String::new();

    // 파일 헤더
    out.push_str("// ═══════════════════════════════════════════════════════════════\n");
    out.push_str("// Auto-generated by x1zzLang `emit rust`\n");
    out.push_str(&format!("// Source: {}\n", source_path));
    out.push_str("//\n");
    out.push_str("// [필요한 Cargo.toml 의존성]\n");
    out.push_str("//   polars      = { version = \"0.53\", features = [\"lazy\", \"csv\"] }\n");
    out.push_str("//   encoding_rs = \"0.8\"\n");
    out.push_str("// ═══════════════════════════════════════════════════════════════\n\n");

    // 임포트
    out.push_str("use polars::prelude::*;\n");
    out.push_str("use encoding_rs::EUC_KR;\n");
    out.push_str("use std::io::Cursor;\n\n");

    // CSV 로더 헬퍼
    out.push_str(&emit_csv_loader_fn());
    out.push('\n');

    // fn main()
    out.push_str("fn main() -> Result<(), Box<dyn std::error::Error>> {\n");

    // TypeDecl → 스키마 주석 블록
    let has_schemas = program
        .stmts
        .iter()
        .any(|s| matches!(s, Stmt::TypeDecl { .. }));
    if has_schemas {
        out.push_str(
            "    // ── x1zzLang Schema Definitions (참조용 주석) ─────────────────────\n",
        );
        for stmt in &program.stmts {
            if let Stmt::TypeDecl { name, fields } = stmt {
                out.push_str(&format!("    // type {} = {{\n", name));
                for f in fields {
                    out.push_str(&format!("    //   {:<14}: {}\n", f.name, f.field_type));
                }
                out.push_str("    // }\n");
            }
        }
        out.push_str(
            "    // ──────────────────────────────────────────────────────────────────\n\n",
        );
    }

    // 변수별 스키마 추적
    let mut var_col_types: HashMap<String, HashMap<String, String>> = HashMap::new();

    // VarDecl → LazyFrame 파이프라인
    for stmt in &program.stmts {
        if let Stmt::VarDecl {
            var_name,
            is_mut,
            source,
            ops,
        } = stmt
        {
            let mut_kw = if *is_mut { "mut " } else { "" };

            // 활성 컬럼 타입 맵 결정
            let col_types: HashMap<String, String> = match source {
                PipelineSource::Load { schema_name, .. } => schema_map
                    .get(schema_name)
                    .map(|fields| {
                        fields
                            .iter()
                            .map(|f| (f.name.clone(), f.field_type.clone()))
                            .collect()
                    })
                    .unwrap_or_default(),
                PipelineSource::VarRef(src_var) => var_col_types
                    .get(src_var.as_str())
                    .cloned()
                    .unwrap_or_default(),
            };

            // 스키마 검증
            if !col_types.is_empty() {
                for op in ops {
                    validate_op_columns(op, &col_types, source_path)?;
                }
            }

            // 코드 생성 헤더
            out.push_str(&format!(
                "    // ── Pipeline: {}v {} ──────────────────────────────────────────\n",
                mut_kw, var_name
            ));

            // 소스 결정
            match source {
                PipelineSource::Load { file_path, schema_name } => {
                    out.push_str(&format!(
                        "    // load(\"{}\") :: {}\n",
                        file_path, schema_name
                    ));
                    out.push_str(&format!(
                        "    let {}{} = load_csv(\"{}\")? // :: {}\n",
                        mut_kw, var_name, file_path, schema_name
                    ));
                    out.push_str("        .lazy()\n");
                }
                PipelineSource::VarRef(src_var) => {
                    out.push_str(&format!(
                        "    let {}{} = {}.clone().lazy()\n",
                        mut_kw, var_name, src_var
                    ));
                }
            }

            // ── 파이프라인 연산자 체이닝 ─────────────────────────────────────
            // GroupBy+agg 패턴: GroupBy를 저장해 두었다가 다음 집계 연산자와 합쳐 출력
            let mut has_count = false;
            let mut pending_group_col: Option<String> = None;

            for op in ops {
                match op {
                    PipelineOp::Filter(expr) => {
                        let polars_expr = to_typed_polars_expr(expr, &col_types);
                        out.push_str(&format!(
                            "        .filter({})  // |> filter({})\n",
                            polars_expr,
                            Codegen::expr_to_xzz(expr)
                        ));
                    }
                    PipelineOp::Select(cols) => {
                        let polars_cols: Vec<String> =
                            cols.iter().map(|c| format!("col(\"{}\")", c)).collect();
                        out.push_str(&format!(
                            "        .select([{}])  // |> select([{}])\n",
                            polars_cols.join(", "),
                            cols.join(", ")
                        ));
                    }
                    PipelineOp::Count(None) => {
                        // count (no arg): 행 수 출력용 플래그만 설정
                        has_count = true;
                    }

                    // ── GroupBy 저장 ───────────────────────────────────────────
                    PipelineOp::GroupBy(group_col) => {
                        pending_group_col = Some(group_col.clone());
                    }

                    // ── 집계 연산자: GroupBy와 함께 또는 단독 ─────────────────
                    PipelineOp::Count(Some(agg_col)) => {
                        if let Some(gc) = pending_group_col.take() {
                            out.push_str(&format!(
                                "        .group_by([col(\"{}\")])\n        .agg([col(\"{}\").count()])  // |> groupBy(\"{}\") |> count(\"{}\")\n",
                                gc, agg_col, gc, agg_col
                            ));
                        } else {
                            out.push_str(&format!(
                                "        .select([col(\"{}\").count()])  // |> count(\"{}\")\n",
                                agg_col, agg_col
                            ));
                        }
                    }
                    PipelineOp::Sum(agg_col) => {
                        if let Some(gc) = pending_group_col.take() {
                            out.push_str(&format!(
                                "        .group_by([col(\"{}\")])\n        .agg([col(\"{}\").sum()])  // |> groupBy(\"{}\") |> sum(\"{}\")\n",
                                gc, agg_col, gc, agg_col
                            ));
                        } else {
                            out.push_str(&format!(
                                "        .select([col(\"{}\").sum()])  // |> sum(\"{}\")\n",
                                agg_col, agg_col
                            ));
                        }
                    }
                    PipelineOp::Mean(agg_col) => {
                        if let Some(gc) = pending_group_col.take() {
                            out.push_str(&format!(
                                "        .group_by([col(\"{}\")])\n        .agg([col(\"{}\").mean()])  // |> groupBy(\"{}\") |> mean(\"{}\")\n",
                                gc, agg_col, gc, agg_col
                            ));
                        } else {
                            out.push_str(&format!(
                                "        .select([col(\"{}\").mean()])  // |> mean(\"{}\")\n",
                                agg_col, agg_col
                            ));
                        }
                    }
                    PipelineOp::Min(agg_col) => {
                        if let Some(gc) = pending_group_col.take() {
                            out.push_str(&format!(
                                "        .group_by([col(\"{}\")])\n        .agg([col(\"{}\").min()])  // |> groupBy(\"{}\") |> min(\"{}\")\n",
                                gc, agg_col, gc, agg_col
                            ));
                        } else {
                            out.push_str(&format!(
                                "        .select([col(\"{}\").min()])  // |> min(\"{}\")\n",
                                agg_col, agg_col
                            ));
                        }
                    }
                    PipelineOp::Max(agg_col) => {
                        if let Some(gc) = pending_group_col.take() {
                            out.push_str(&format!(
                                "        .group_by([col(\"{}\")])\n        .agg([col(\"{}\").max()])  // |> groupBy(\"{}\") |> max(\"{}\")\n",
                                gc, agg_col, gc, agg_col
                            ));
                        } else {
                            out.push_str(&format!(
                                "        .select([col(\"{}\").max()])  // |> max(\"{}\")\n",
                                agg_col, agg_col
                            ));
                        }
                    }

                    // ── 정렬 / 슬라이싱 ────────────────────────────────────────
                    PipelineOp::OrderBy { col: sort_col, desc } => {
                        out.push_str(&format!(
                            "        .sort([\"{}\"], SortMultipleOptions::default().with_order_descending({}))  // |> orderBy(\"{}\", desc: {})\n",
                            sort_col, desc, sort_col, desc
                        ));
                    }
                    PipelineOp::Take(n) => {
                        out.push_str(&format!(
                            "        .limit({})  // |> take({})\n",
                            n, n
                        ));
                    }

                    // ── Null 처리 ──────────────────────────────────────────────
                    PipelineOp::DropNull(drop_col) => {
                        out.push_str(&format!(
                            "        .drop_nulls(Some(vec![col(\"{}\")]))  // |> dropNull(\"{}\")\n",
                            drop_col, drop_col
                        ));
                    }
                    PipelineOp::FillNull { col: fill_col, value } => {
                        let lit_str = match value {
                            FillNullValue::Int(n)   => format!("lit({}i64)", n),
                            FillNullValue::Float(f) => format!("lit({}f64)", f),
                            FillNullValue::Str(s)   => format!("lit(\"{}\")", s),
                        };
                        out.push_str(&format!(
                            "        .with_columns([col(\"{}\").fill_null({})])  // |> fillNull(\"{}\", ...)\n",
                            fill_col, lit_str, fill_col
                        ));
                    }
                }
            }

            // collect
            out.push_str("        .collect()?;\n");

            // 결과 출력
            if has_count {
                out.push_str(&format!(
                    "    println!(\"[{}] count = {{}}\", {}.height());\n",
                    var_name, var_name
                ));
            } else {
                out.push_str(&format!(
                    "    println!(\"[{}]\\n{{}}\", {});\n",
                    var_name, var_name
                ));
            }
            out.push('\n');

            if !col_types.is_empty() {
                var_col_types.insert(var_name.clone(), col_types);
            }
        }
    }

    out.push_str("    Ok(())\n");
    out.push_str("}\n");

    Ok(out)
}

// ─────────────────────────────────────────────────────────────────────────────
// ── 스키마 기반 컬럼명 검증 ────────────────────────────────────────────────────
// ─────────────────────────────────────────────────────────────────────────────

fn validate_op_columns(
    op: &PipelineOp,
    col_types: &HashMap<String, String>,
    source_path: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    // 컬럼명을 스키마에서 검사하는 내부 헬퍼
    let check_col = |col_name: &str| -> Result<(), Box<dyn std::error::Error>> {
        if !col_types.contains_key(col_name) {
            let available: Vec<&str> = col_types.keys().map(String::as_str).collect();
            let suggestion = find_closest_col(col_name, &available).unwrap_or(col_name);
            return Err(format!(
                "[SchemaError] at {}\n\
                 ─────────────────────────────────────────────\n\
                 Cause   : 선언되지 않은 컬럼이 있습니다.\n\
                 Detail  : column '{}' not found in schema\n\
                 Available: {}\n\
                 → Did you mean: col(\"{}\")",
                source_path,
                col_name,
                available.join(", "),
                suggestion
            )
            .into());
        }
        Ok(())
    };

    match op {
        PipelineOp::Filter(expr) => {
            validate_expr_columns(expr, col_types, source_path)?;
        }
        PipelineOp::Select(cols) => {
            for col_name in cols {
                check_col(col_name.as_str())?;
            }
        }
        // 컬럼 인수가 없는 연산자
        PipelineOp::Count(None) => {}
        PipelineOp::Take(_) => {}

        // 문자열 컬럼 인수를 갖는 연산자 — 모두 스키마 검증
        PipelineOp::Count(Some(col))
        | PipelineOp::GroupBy(col)
        | PipelineOp::Sum(col)
        | PipelineOp::Mean(col)
        | PipelineOp::Min(col)
        | PipelineOp::Max(col)
        | PipelineOp::DropNull(col) => {
            check_col(col.as_str())?;
        }
        PipelineOp::OrderBy { col, .. } => {
            check_col(col.as_str())?;
        }
        PipelineOp::FillNull { col, .. } => {
            check_col(col.as_str())?;
        }
    }
    Ok(())
}

fn validate_expr_columns(
    expr: &Expr,
    col_types: &HashMap<String, String>,
    source_path: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    match expr {
        Expr::Ident(col_name) => {
            if !col_types.contains_key(col_name.as_str()) {
                let available: Vec<&str> = col_types.keys().map(String::as_str).collect();
                let suggestion =
                    find_closest_col(col_name, &available).unwrap_or(col_name);
                return Err(format!(
                    "[SchemaError] at {}\n\
                     ─────────────────────────────────────────────\n\
                     Cause   : filter() 에 선언되지 않은 컬럼이 있습니다.\n\
                     Detail  : column '{}' not found in schema\n\
                     Available: {}\n\
                     → Did you mean: col(\"{}\")",
                    source_path,
                    col_name,
                    available.join(", "),
                    suggestion
                )
                .into());
            }
            Ok(())
        }
        Expr::BinOp { lhs, rhs, .. } => {
            validate_expr_columns(lhs, col_types, source_path)?;
            if matches!(rhs.as_ref(), Expr::Ident(_)) {
                validate_expr_columns(rhs, col_types, source_path)?;
            }
            Ok(())
        }
        _ => Ok(()),
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// ── 타입 인식 Polars 표현식 생성 ──────────────────────────────────────────────
// ─────────────────────────────────────────────────────────────────────────────

fn to_typed_polars_expr(expr: &Expr, col_types: &HashMap<String, String>) -> String {
    match expr {
        Expr::Ident(s) => format!("col(\"{}\")", s),
        Expr::StringLit(s) => format!("lit(\"{}\")", s),
        Expr::IntLit(n) => format!("lit({}i64)", n),
        Expr::FloatLit(f) => format!("lit({}f64)", f),
        Expr::BoolLit(b) => format!("lit({})", b),
        Expr::BinOp { lhs, op, rhs } => {
            let lhs_is_float = if let Expr::Ident(col_name) = lhs.as_ref() {
                col_types
                    .get(col_name.as_str())
                    .map(|t| t.contains("float"))
                    .unwrap_or(false)
            } else {
                false
            };

            let l = to_typed_polars_expr(lhs, col_types);

            let r = if lhs_is_float {
                match rhs.as_ref() {
                    Expr::IntLit(n) => format!("lit({:.1}f64)", *n as f64),
                    Expr::FloatLit(f) => format!("lit({}f64)", f),
                    other => to_typed_polars_expr(other, col_types),
                }
            } else {
                to_typed_polars_expr(rhs, col_types)
            };

            let op_method = match op {
                BinOpKind::Eq    => "eq",
                BinOpKind::NotEq => "neq",
                BinOpKind::Lt    => "lt",
                BinOpKind::Gt    => "gt",
                BinOpKind::LtEq  => "lt_eq",
                BinOpKind::GtEq  => "gt_eq",
            };
            format!("{}.{}({})", l, op_method, r)
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// ── 오타 힌트: 편집 거리 기반 컬럼명 제안 ───────────────────────────────────────
// ─────────────────────────────────────────────────────────────────────────────

fn find_closest_col<'a>(name: &str, candidates: &[&'a str]) -> Option<&'a str> {
    candidates
        .iter()
        .min_by_key(|&&c| edit_distance(name, c))
        .copied()
}

fn edit_distance(a: &str, b: &str) -> usize {
    let a: Vec<char> = a.chars().collect();
    let b: Vec<char> = b.chars().collect();
    let (m, n) = (a.len(), b.len());
    let mut dp = vec![vec![0usize; n + 1]; m + 1];
    for i in 0..=m { dp[i][0] = i; }
    for j in 0..=n { dp[0][j] = j; }
    for i in 1..=m {
        for j in 1..=n {
            dp[i][j] = if a[i - 1] == b[j - 1] {
                dp[i - 1][j - 1]
            } else {
                1 + dp[i - 1][j].min(dp[i][j - 1]).min(dp[i - 1][j - 1])
            };
        }
    }
    dp[m][n]
}

// ─────────────────────────────────────────────────────────────────────────────
// ── 생성된 파일에 포함될 CSV 로더 헬퍼 함수 소스 ──────────────────────────────
// ─────────────────────────────────────────────────────────────────────────────

fn emit_csv_loader_fn() -> String {
    r#"/// EUC-KR(CP949) 자동 감지 CSV 로더
/// UTF-8 직접 시도 → 실패 시 EUC-KR 디코딩 (한국 공공데이터 대응)
fn load_csv(file_path: &str) -> Result<DataFrame, Box<dyn std::error::Error>> {
    let raw_bytes = std::fs::read(file_path)?;

    // UTF-8 직접 시도 → 실패 시 EUC-KR(CP949) 디코딩
    let utf8_string = match String::from_utf8(raw_bytes.clone()) {
        Ok(s) => s,
        Err(_) => {
            let (cow, _, _) = EUC_KR.decode(&raw_bytes);
            cow.into_owned()
        }
    };

    let cursor = Cursor::new(utf8_string.into_bytes());
    let df = CsvReadOptions::default()
        .with_infer_schema_length(Some(200))
        .with_parse_options(
            CsvParseOptions::default()
                .with_null_values(Some(NullValues::AllColumnsSingle("-".into()))),
        )
        .into_reader_with_file_handle(cursor)
        .finish()?;

    Ok(df)
}
"#
    .to_string()
}
