// ═══════════════════════════════════════════════════════════════
// Auto-generated by x1zzLang `emit rust`
// Source: examples/poc_correct.xzz
//
// [필요한 Cargo.toml 의존성]
//   polars      = { version = "0.53", features = ["lazy", "csv"] }
//   encoding_rs = "0.8"
// ═══════════════════════════════════════════════════════════════

use polars::prelude::*;
use encoding_rs::EUC_KR;
use std::io::Cursor;

/// EUC-KR(CP949) 자동 감지 CSV 로더
/// UTF-8 직접 시도 → 실패 시 EUC-KR 디코딩 (한국 공공데이터 대응)
fn load_csv(file_path: &str) -> Result<DataFrame, Box<dyn std::error::Error>> {
    let raw_bytes = std::fs::read(file_path)?;

    // UTF-8 직접 시도 → 실패 시 EUC-KR(CP949) 디코딩
    let utf8_string = match String::from_utf8(raw_bytes.clone()) {
        Ok(s) => s,
        Err(_) => {
            let (cow, _, _) = EUC_KR.decode(&raw_bytes);
            cow.into_owned()
        }
    };

    let cursor = Cursor::new(utf8_string.into_bytes());
    let df = CsvReadOptions::default()
        .with_infer_schema_length(Some(200))
        .with_parse_options(
            CsvParseOptions::default()
                .with_null_values(Some(NullValues::AllColumnsSingle("-".into()))),
        )
        .into_reader_with_file_handle(cursor)
        .finish()?;

    Ok(df)
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    // ── x1zzLang Schema Definitions (참조용 주석) ─────────────────────
    // type AirQuality = {
    //   date          : string
    //   station       : string
    //   pm10          : Option<float>
    //   pm25          : Option<float>
    // }
    // ──────────────────────────────────────────────────────────────────

    // ── Pipeline: v air_raw ────────────────────────────────────────────
    // load("examples/seoul_air_2008_2011.csv") :: AirQuality
    let air_raw = load_csv("examples/seoul_air_2008_2011.csv")? // :: AirQuality
        .lazy()
        .filter(col("pm10").gt(lit(50.0f64)))  // |> filter(pm10 > 50)
        .select([col("date"), col("station"), col("pm10"), col("pm25")])  // |> select([date, station, pm10, pm25])
        .collect()?;
    println!("[air_raw]\n{}", air_raw);

    // ── Pipeline: v air_filtered ────────────────────────────────────────────
    let air_filtered = air_raw.clone().lazy()
        .filter(col("pm25").gt(lit(10.0f64)))  // |> filter(pm25 > 10)
        .collect()?;
    println!("[air_filtered] count = {}", air_filtered.height());

    // ── Pipeline: v air_raw2 ────────────────────────────────────────────
    // load("examples/seoul_air_2026.csv") :: AirQuality
    let air_raw2 = load_csv("examples/seoul_air_2026.csv")? // :: AirQuality
        .lazy()
        .filter(col("pm10").gt(lit(20.0f64)))  // |> filter(pm10 > 20)
        .filter(col("pm25").gt(lit(10.0f64)))  // |> filter(pm25 > 10)
        .select([col("date"), col("station"), col("pm10"), col("pm25")])  // |> select([date, station, pm10, pm25])
        .collect()?;
    println!("[air_raw2] count = {}", air_raw2.height());

    Ok(())
}
